services:
  builder:
    build: .
    working_dir: /app
    privileged: true
    stdin_open: true
    tty: true
    environment:
      CI: "1"
      DEBIAN_FRONTEND: noninteractive
      APT_LOCK_TIMEOUT: "600"
    volumes:
      - .:/app
      - /dev:/dev
    command: /bin/bash
