#!/bin/sh
# auto/config — live-build configuration
# Base: Linux Mint 22 Cinnamon (Ubuntu 24.04 / noble)

lb config noauto \
    --architectures amd64 \
    --distribution noble \
    --archive-areas "main restricted universe multiverse" \
    --parent-distribution noble \
    --parent-archive-areas "main restricted universe multiverse" \
    --mirror-bootstrap "http://archive.ubuntu.com/ubuntu" \
    --mirror-chroot "http://archive.ubuntu.com/ubuntu" \
    --mirror-binary "http://archive.ubuntu.com/ubuntu" \
    --debootstrap-options "--variant=minbase" \
    --linux-flavours "generic" \
    --binary-images iso-hybrid \
    --bootloaders "grub-efi" \
    --uefi-secure-boot enable \
    --mode ubuntu \
    --system live \
    --iso-application "CaramOS" \
    --iso-publisher "Vietnam Linux Family" \
    --iso-volume "CaramOS 0.1" \
    "${@}"
