#!/bin/sh
if [ "$1" = "configure" ]; then
    # Compile gsettings schemas
    if [ -x /usr/bin/glib-compile-schemas ]; then
        glib-compile-schemas /usr/share/glib-2.0/schemas/ || true
    fi
fi
